services:
  build:
    image: ghcr.io/systemed/tilemaker:master
    volumes:
      - .:/src
    working_dir: /src

  server:
    image: maptiler/tileserver-gl:latest
    command:
      - --port
      - "${PORT:-8080}"
      - --config
      - "config.json"
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - .:/src
    working_dir: /src

  design:
    image: maputnik/editor
    ports:
      - "8081:8888"
    command:
      - maputnik
      - --file
      - "/styles/world.json"
      - --watch
    volumes:
      - ./styles:/styles
      - ./build:/build
