services:
  tippecanoe:
    image: ghcr.io/bkeepers/tippecanoe:main
    volumes:
      - .:/src
    working_dir: /src
    init: true # Ensure proper signal handling

  gdal:
    image: ghcr.io/osgeo/gdal:ubuntu-small-latest
    volumes:
      - .:/src
    working_dir: /src
    init: true # Ensure proper signal handling

  tilemaker:
    image: ghcr.io/systemed/tilemaker:master
    volumes:
      - .:/src
    working_dir: /src
    init: true # Ensure proper signal handling
    entrypoint: /usr/src/app/tilemaker

  server:
    image: maptiler/tileserver-gl:latest
    command:
      - --port
      - "${PORT:-8080}"
      - --config
      - "config.json"
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - .:/src
    working_dir: /src

  editor:
    image: maputnik/editor
    ports:
      - "8081:8888"
    command:
      - maputnik
      - --file
      - "/styles/world.json"
      - --watch
    volumes:
      - ./styles:/styles
      - ./build:/build
